import google.generativeai as genai
import os

# তোমার API Key এখানে বসান
genai.configure(api_key="YOUR_GEMINI_API_KEY")

model = genai.GenerativeModel('gemini-1.5-pro')

# তোমার GitHub রিপোজিটরি থেকে কোড লোড করা
def get_context():
    try:
        with open('app/src/main/java/com/example/bkashhacktool/MainActivity.kt', 'r') as f:
            code = f.read()
        return code
    except FileNotFoundError:
        return "File not found"

# AI থেকে নতুন কোড জেনারেট করা
def generate_new_feature():
    prompt = """
    Here is the current MainActivity.kt code:
    """ + get_context() + """
    
    Please add a new function called 'checkBalance()' using OkHttp.
    Return only the Kotlin code for the new function.
    """
    
    response = model.generate_content(prompt)
    return response.text

if __name__ == "__main__":
    new_code = generate_new_feature()
    print(new_code)
    
    # নতুন কোডটি ফাইলে অ্যাপেন্ড করা
    with open('app/src/main/java/com/example/bkashhacktool/MainActivity.kt', 'a') as f:
        f.write("\n\n// Generated by Gemini AI\n" + new_code)
